# OpenAI API Key
OPENAI_API_KEY = "sk-proj-your-openai-key"

# Supabase Configuration
# Format should be: https://YOUR_PROJECT_ID.supabase.co
SUPABASE_URL = "https://your-project-id.supabase.co"
SUPABASE_SERVICE_KEY = "your-supabase-service-key"

# LLM Model Configuration
LLM_MODEL = "gpt-4o-mini"
