
# Supabase Configuration
# Format should be: https://YOUR_PROJECT_ID.supabase.co
SUPABASE_URL=https://wnzplxjppzfnirfjgvxk.supabase.co
SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduenBseGpwcHpmbmlyZmpndnhrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNzcwMjYxOCwiZXhwIjoyMDUzMjc4NjE4fQ.VTPMg6uD9io1cb4Ch3itPH7B9m76GJk1f4ja-QgtWco

# LLM Model Configuration
LLM_MODEL=gpt-4o-mini

# Optional: Deployment Environment
DEPLOYMENT_ENV=streamlit_sharing
